//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPERACION_YMF.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public string NRO_CUENTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
    }
}
